## **Convertendo Tipos de Dados em um DataFrame**

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('chemical-dependence-treatment-program-admissions-beginning-2007.csv.zip')
df.head()

,Year,County of Program Location,Program Category,Service Type,Age Group,Primary Substance Group,Admissions
0,2007,Albany,Crisis,Medical Managed Detoxification,Under 18,Heroin,4
1,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,Alcohol,35
2,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,Heroin,132
3,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,Other Opioids,6
4,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,All Others,2

In [5]:
df.dtypes

Year                           int64
County of Program Location    object
Program Category              object
Service Type                  object
Age Group                     object
Primary Substance Group       object
Admissions                     int64
dtype: object

In [6]:
df['Admissions'] = df['Admissions'].astype('Float64')
df.head()

,Year,County of Program Location,Program Category,Service Type,Age Group,Primary Substance Group,Admissions
0,2007,Albany,Crisis,Medical Managed Detoxification,Under 18,Heroin,4.0
1,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,Alcohol,35.0
2,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,Heroin,132.0
3,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,Other Opioids,6.0
4,2007,Albany,Crisis,Medical Managed Detoxification,18 thru 24,All Others,2.0