## **Normalização ou Padronização**

**Normalizar**

X' = ( X - Xmin ) / ( Xmax - Xmin )

Valores São Normalizados entre ( 0, 1 )

**Padronizar ou Z-Score Normalizaton** - https://www.youtube.com/watch?v=-LC_PKBoZfk

**Mean / Standard Deviation**\
X' = ( X - Xmédia ) / DesvPad  =>  Média fica igual a 0 e o Desvio Padrão igual a 1

**Mean / Mean Absolute Deviation**\
Mean Absolute Deviation = **A**\
**A** = ( ( X1 - Xmédia ) + ( X2 - Xmédia ) + ... ( Xn - Xmédia ) )\
X1 = ( X - Xmédia ) / A

In [1]:
# Importação dos Módulos
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Carga dos Dados
dados = pd.read_csv( 'pima-data.csv')
dados.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148,72,35,0,33.6,0.627,50,1.3790,True
1,1,85,66,29,0,26.6,0.351,31,1.1426,False
2,8,183,64,0,0,23.3,0.672,32,0.0000,True
3,1,89,66,23,94,28.1,0.167,21,0.9062,False
4,0,137,40,35,168,43.1,2.288,33,1.3790,True

In [3]:
# Componentes de input (X) e output (y)
X = dados.drop(columns=['diabetes'])
y = dados['diabetes']

### **Normalização**

In [4]:
# Gerando a nova escala - Normalização
scaler = MinMaxScaler(feature_range=(0,1))
X_scaler = scaler.fit_transform(X)

In [5]:
print('Dados Originais\n:', dados.drop(columns=['diabetes']).values)
print('Dados Normalizados\n:', X_scaler[:, 0:5])

Dados Originais
: [[  6.     148.      72.     ...   0.627   50.       1.379 ]
 [  1.      85.      66.     ...   0.351   31.       1.1426]
 [  8.     183.      64.     ...   0.672   32.       0.    ]
 ...
 [  5.     121.      72.     ...   0.245   30.       0.9062]
 [  1.     126.      60.     ...   0.349   47.       0.    ]
 [  1.      93.      70.     ...   0.315   23.       1.2214]]
Dados Normalizados
: [[0.35294118 0.74371859 0.59016393 0.35353535 0.        ]
 [0.05882353 0.42713568 0.54098361 0.29292929 0.        ]
 [0.47058824 0.91959799 0.52459016 0.         0.        ]
 ...
 [0.29411765 0.6080402  0.59016393 0.23232323 0.13238771]
 [0.05882353 0.63316583 0.49180328 0.         0.        ]
 [0.05882353 0.46733668 0.57377049 0.31313131 0.        ]]

### **Padronização**

#### **Z-Score - Normalization ( Mean / Standard Deviation )**

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scalerP = scaler.fit_transform(X)

In [7]:
print('Dados Originais\n:', dados.drop(columns=['diabetes']).values)
print('Dados Padronizados\n:', X_scalerP[:, 0:5])

Dados Originais
: [[  6.     148.      72.     ...   0.627   50.       1.379 ]
 [  1.      85.      66.     ...   0.351   31.       1.1426]
 [  8.     183.      64.     ...   0.672   32.       0.    ]
 ...
 [  5.     121.      72.     ...   0.245   30.       0.9062]
 [  1.     126.      60.     ...   0.349   47.       0.    ]
 [  1.      93.      70.     ...   0.315   23.       1.2214]]
Dados Padronizados
: [[ 0.63994726  0.84832379  0.14964075  0.90726993 -0.69289057]
 [-0.84488505 -1.12339636 -0.16054575  0.53090156 -0.69289057]
 [ 1.23388019  1.94372388 -0.26394125 -1.28821221 -0.69289057]
 ...
 [ 0.3429808   0.00330087  0.14964075  0.15453319  0.27959377]
 [-0.84488505  0.1597866  -0.47073225 -1.28821221 -0.69289057]
 [-0.84488505 -0.8730192   0.04624525  0.65635768 -0.69289057]]

## **Resultado da Máquina Preditiva Sem Redimensionamento**

In [7]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [8]:
# Carga dos Dados
dados = pd.read_csv( 'pima-data.csv')

In [9]:
# Separando os dados
X = dados.drop(columns=['diabetes'], axis=1)
y = dados['diabetes']

In [20]:
# Definindo os Valores para os Números de Folds
num_folds = 10
random_state = 7

In [21]:
# Separando os dados em Folds
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=random_state)

In [41]:
# Criando o modelo
modelo = KNeighborsClassifier()

# Cross Validation
resultados = cross_val_score(modelo, X, y, cv=kfold)

# Resultado
print('Acurácia: %.3f' % (resultados.mean() * 100))

Acurácia: 71.099

## **Resultado com Padronização**

In [40]:
scaler = StandardScaler()
X_scaler = scaler.fit_transform(X)

# Criando o modelo
modelo = KNeighborsClassifier()

# Cross Validation
resultados = cross_val_score(modelo, X_scaler, y, cv=kfold)

# Resultado
print('Acurácia: %.3f' % (resultados.mean() * 100))

Acurácia: 75.395

## **Resultado com Normalização**

In [42]:
scaler = MinMaxScaler(feature_range=(0,1))
X_scaler = scaler.fit_transform(X)

# Criando o modelo
modelo = KNeighborsClassifier()

# Cross Validation
resultados = cross_val_score(modelo, X_scaler, y, cv=kfold)

# Resultado
print('Acurácia: %.3f' % (resultados.mean() * 100))

Acurácia: 73.835

## **Z-Score - Normalization ( Mean / Mean Absolut Deviation )**

In [12]:
# Carga dos Dados
dados = pd.read_csv( 'pima-data.csv')
dados.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148,72,35,0,33.6,0.627,50,1.3790,True
1,1,85,66,29,0,26.6,0.351,31,1.1426,False
2,8,183,64,0,0,23.3,0.672,32,0.0000,True
3,1,89,66,23,94,28.1,0.167,21,0.9062,False
4,0,137,40,35,168,43.1,2.288,33,1.3790,True

In [11]:
import numpy as np

def z_score_mad(data):
    mean = np.mean(data)
    mad = np.mean(np.abs(data - mean))  # MAD
    z_scores = (data - mean) / mad
    return z_scores

In [ ]:
colunas = dados.columns.drop('diabetes')
z_score = z_score_mad(dados[colunas])
z_score['diabetes'] = dados['diabetes']

z_score.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,-0.874969,2.771027,0.819649,-0.130364,-1.029025,-0.166311,-1.012926,0.254776,-0.993618,True
1,-1.003349,1.153437,0.665593,-0.284420,-1.029025,-0.346043,-1.020013,-0.233068,-0.999688,False
2,-0.823617,3.669687,0.614240,-1.029025,-1.029025,-0.430774,-1.011771,-0.207392,-1.029025,True
3,-1.003349,1.256141,0.665593,-0.438476,1.384521,-0.307529,-1.024737,-0.489829,-1.005757,False
4,-1.029025,2.488590,-0.001984,-0.130364,3.284547,0.077612,-0.970278,-0.181716,-0.993618,True

In [22]:
X = z_score.drop(columns=['diabetes'], axis=1)
y = z_score['diabetes']

modelo = KNeighborsClassifier()

# Cross Validation
resultados = cross_val_score(modelo, X, y, cv=kfold)

# Resultado
print('Acurácia: %.3f' % (resultados.mean() * 100))

Acurácia: 71.099